// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9505baf036887c87e752cbc7b1e137f8b2f023e4/react-color/lib/components/circle/Circle.d.ts
declare module 'react-color/lib/components/circle/circle' {
import { Component } from 'react';
import { ColorPickerProps } from 'react-color';

export interface CirclePickerProps extends ColorPickerProps<CirclePicker> {
    colors?: string[];
    width?: string;
}

export default class CirclePicker extends Component<CirclePickerProps, any> {}
}
