// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/767cdfc00c03e941639790d53b1f72ad7e424127/react-color/index.d.ts
declare module 'react-color' {
// Type definitions for react-color 2.11
// Project: https://github.com/casesandberg/react-color/
// Definitions by: Karol Janyst <https://github.com/LKay>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.1

import { ComponentClass, ClassAttributes, StatelessComponent, ReactNode } from 'react';

export interface HSLColor {
    a?: number;
    h: number;
    l: number;
    s: number;
}

export interface RGBColor {
    a?: number;
    b: number;
    g: number;
    r: number;
}

export type Color = string | HSLColor | RGBColor;

export interface ColorResult {
    hex: string;
    hsl: HSLColor;
    rgb: RGBColor;
}

export type ColorChangeHandler = (color: ColorResult) => void;

export interface ColorPickerProps<A> extends ClassAttributes<A> {
    color?: Color;
    onChange?: ColorChangeHandler;
    onChangeComplete?: ColorChangeHandler;
}

export interface CustomPickerProps<A> extends ClassAttributes<A> {
    color?: Color;
    pointer?: ReactNode;
    onChange: ColorChangeHandler;
}

export { default as AlphaPicker, AlphaPickerProps } from 'react-color/lib/components/alpha/alpha';
export { default as BlockPicker, BlockPickerProps } from 'react-color/lib/components/block/block';
export { default as ChromePicker, ChromePickerProps } from 'react-color/lib/components/chrome/chrome';
export { default as CirclePicker, CirclePickerProps } from 'react-color/lib/components/circle/circle';
export { default as CompactPicker, CompactPickerProps } from 'react-color/lib/components/compact/compact';
export { default as GithubPicker, GithubPickerProps } from 'react-color/lib/components/github/github';
export { default as HuePicker, HuePickerProps } from 'react-color/lib/components/hue/hue';
export { default as MaterialPicker, MaterialPickerProps } from 'react-color/lib/components/material/material';
export { default as PhotoshopPicker, PhotoshopPickerProps } from 'react-color/lib/components/photoshop/photoshop';
export { default as SketchPicker, SketchPickerProps } from 'react-color/lib/components/sketch/sketch';
export { default as SliderPicker, SliderPickerProps } from 'react-color/lib/components/slider/slider';
export { default as SwatchesPicker, SwatchesPickerProps } from 'react-color/lib/components/swatches/swatches';
export { default as CustomPicker, InjectedColorProps } from 'react-color/lib/components/common/colorwrap';
}
