// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9505baf036887c87e752cbc7b1e137f8b2f023e4/react-color/lib/components/alpha/Alpha.d.ts
declare module 'react-color/lib/components/alpha/alpha' {
import { Component } from 'react';
import { ColorPickerProps } from 'react-color';

export interface AlphaPickerProps extends ColorPickerProps<AlphaPicker> {
    height?: string;
    width?: string;
}

export default class AlphaPicker extends Component<AlphaPickerProps, any> {}
}
