// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9505baf036887c87e752cbc7b1e137f8b2f023e4/react-color/lib/components/photoshop/Photoshop.d.ts
declare module 'react-color/lib/components/photoshop/photoshop' {
import { Component } from 'react';
import { ColorChangeHandler, ColorPickerProps } from 'react-color';

export interface PhotoshopPickerProps extends ColorPickerProps<PhotoshopPicker> {
    header?: string;
    onAccept?: ColorChangeHandler;
    onCancel?: ColorChangeHandler;
}

export default class PhotoshopPicker extends Component<PhotoshopPickerProps, any> {}
}
