// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9505baf036887c87e752cbc7b1e137f8b2f023e4/react-color/lib/components/hue/Hue.d.ts
declare module 'react-color/lib/components/hue/hue' {
import { Component } from 'react';
import { ColorPickerProps } from 'react-color';

export interface HuePickerProps extends ColorPickerProps<HuePicker> {
    height?: string;
    width?: string;
}

export default class HuePicker extends Component<HuePickerProps, any> {}
}
