// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9505baf036887c87e752cbc7b1e137f8b2f023e4/react-color/lib/components/slider/Slider.d.ts
declare module 'react-color/lib/components/slider/slider' {
import { Component } from 'react';
import { ColorPickerProps } from 'react-color';

export type SliderPickerProps = ColorPickerProps<SliderPicker>;

export default class SliderPicker extends Component<SliderPickerProps, any> {}
}
