// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9505baf036887c87e752cbc7b1e137f8b2f023e4/react-color/lib/components/chrome/Chrome.d.ts
declare module 'react-color/lib/components/chrome/chrome' {
import { Component } from 'react';
import { ColorPickerProps } from 'react-color';

export interface ChromePickerProps extends ColorPickerProps<ChromePicker> {
    disableAlpha?: boolean;
}

export default class ChromePicker extends Component<ChromePickerProps, any> {}
}
