// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9505baf036887c87e752cbc7b1e137f8b2f023e4/react-color/lib/components/swatches/Swatches.d.ts
declare module 'react-color/lib/components/swatches/swatches' {
import { Component } from 'react';
import { ColorPickerProps } from 'react-color';

export interface SwatchesPickerProps extends ColorPickerProps<SwatchesPicker> {
    colors?: string[][];
    height?: number;
    width?: number;
}

export default class SwatchesPicker extends Component<SwatchesPickerProps, any> {}
}
