// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9505baf036887c87e752cbc7b1e137f8b2f023e4/react-color/lib/components/common/ColorWrap.d.ts
declare module 'react-color/lib/components/common/colorwrap' {
import { ComponentClass, StatelessComponent } from 'react';
import { HSLColor, RGBColor, ColorChangeHandler } from 'react-color';

export interface InjectedColorProps {
    hex?: string;
    hsl?: HSLColor;
    rgb?: RGBColor;
    onChange?: ColorChangeHandler;
}

export default function CustomPicker<A>(component: ComponentClass<A> | StatelessComponent<A>): ComponentClass<A & InjectedColorProps>;
}
