/**
 * Wegas
 * http://wegas.albasim.ch
 *
 * Copyright (c) 2013-2021 School of Management and Engineering Vaud, Comem, MEI
 * Licensed under the MIT License
 */

import { IconName } from '@fortawesome/free-solid-svg-icons';

//export const colors = [
//  'white-orange', 'light-orange', 'orange', 'dark-orange', 'black-orange', 'white-red', 'light-red', 'red', 'dark-red', 'black-red', 'white-bluepurple', 'light-bluepurple', 'bluepurple', 'dark-bluepurple', 'black-bluepurple', 'white-greenblue', 'light-greenblue', 'greenblue', 'dark-greenblue', 'black-greenblue', 'white-grey', 'light-grey', 'grey', 'dark-grey', 'black-grey', 'white-yellow', 'light-yellow', 'yellow', 'dark-yellow', 'black-yellow', 'white-purple', 'light-purple', 'purple', 'dark-purple', 'black-purple', 'white-blue', 'light-blue', 'blue', 'dark-blue', 'black-blue', 'white-greenyellow', 'light-greenyellow', 'greenyellow', 'dark-greenyellow', 'black-greenyellow', 'white-brown', 'light-brown', 'brown', 'dark-brown', 'black-brown', 'white-orangine', 'light-orangine', 'orangine', 'dark-orangine', 'black-orangine', 'white-pink', 'light-pink', 'pink', 'dark-pink', 'black-pink', 'white-ocean', 'light-ocean', 'ocean', 'dark-ocean', 'black-ocean', 'white-green', 'light-green', 'green', 'dark-green', 'black-green', 'white-wine', 'light-wine', 'wine', 'dark-wine', 'black-wine'] as const;
//
//export type IconColor = typeof colors[number];

export const verifiedIllu = 'ICON_grey_id-card_far';
export const userIllu = 'ICON_grey_user_fa';

export const fontelloName = [
  'emo-angry',
  'emo-grin',
  'emo-beer',
  'emo-saint',
  'emo-cry',
  'emo-shoot',
  'emo-squint',
  'emo-laugh',
  'emo-displeased',
  'emo-sunglasses',
  'emo-coffee',
  'emo-tongue',
  'emo-surprised',
  'emo-devil',
  'emo-thumbsup',
  'emo-sleep',
  'emo-unhappy',
  'emo-wink2',
  'emo-wink',
  'emo-happy',
  'note',
  'note-beamed',
  'flashlight',
  'heart',
  'user',
  'video',
  'picture',
  'camera',
  'tag',
  'comment',
  'book',
  'hourglass',
  'sound',
  'lock',
  'lock-open',
  'pencil',
  'feather',
  'print',
  'info',
  'share',
  'tools',
  'bell',
  'alert',
  'chat',
  'folder',
  'archive',
  'box',
  'bookmark',
  'bookmarks',
  'compass',
  'basket',
  'lamp',
  'light-up',
  'trophy',
  'battery',
  'back-in-time',
  'monitor',
  'mobile',
  'palette',
  'signal',
  'progress-3',
  'progress-2',
  'progress-1',
  'book-open',
  'newspaper',
  'doc-text-inv',
  'doc-text',
  'mic',
  'chart-pie',
  'chart-line',
  'chart-bar',
  'chart-area',
  'cloud-thunder',
  'globe',
  'network',
  'cd',
  'magnet',
  'brush',
  'infinity',
  'key',
  'bucket',
  'database',
  'megaphone',
  'clipboard',
  'floppy',
  'credit-card',
  'droplet',
  'water',
  'air',
  'ticket',
  'graduation-cap',
  'tape',
  'flash',
  'moon',
  'flight',
  'lifebuoy',
  'mouse',
  'briefcase',
  'suitcase',
  'dot',
  'dot-2',
  'dot-3',
  'flow-tree',
  'flow-branch',
  'flow-cascade',
  'flow-line',
  'gauge',
  'flow-parallel',
  'thermometer',
  'list-add',
  'list',
  'target',
  'play',
  'stop',
  'pause',
  'record',
  'to-end',
  'to-start',
  'fast-forward',
  'fast-backward',
  'bag',
  'calendar',
  'docs',
  'doc',
  'doc-landscape',
  'code',
  'user-outline',
  'user-1',
  'users-outline',
  'users',
  'user-add-outline',
  'user-add',
  'user-delete-outline',
  'user-delete',
  'video-1',
  'videocam-outline',
  'videocam',
  'picture-outline',
  'picture-1',
  'camera-outline',
  'camera-1',
  'th-outline',
  'th',
  'th-large-outline',
  'th-large',
  'th-list-outline',
  'th-list',
  'anchor',
  'pi',
  'chart-pie-alt',
  'chart-pie-1',
  'aperture',
  'aperture-alt',
  'steering-wheel',
  'book-1',
  'brush-1',
  'brush-alt',
  'equalizer',
  'chart-bar-1',
  'umbrella',
  'moon-inv',
  'mobile-1',
  'split',
  'target-1',
  'calendar-1',
  'wrench',
  'bullhorn',
  'award',
  'signal-1',
  'money',
  'dollar',
  'lock-1',
  'lock-open-1',
  'home',
  'trash',
  'videocam-alt',
  'camera-2',
  'videocam-1',
  'windy-rain-inv',
  'snow-inv',
  'snow-heavy-inv',
  'hail-inv',
  'clouds-inv',
  'clouds-flash-inv',
  'temperature',
  'compass-1',
  'cloud-sun-inv',
  'cloud-moon-inv',
  'cloud-flash-inv',
  'cloud-inv',
  'drizzle-inv',
  'rain-inv',
  'windy-inv',
  'sun-inv',
  'moon-inv-1',
  'ruler',
  'fire',
  'trophy-1',
  'female',
  'male',
  'spread',
  'king',
  'monitor-1',
  'coverflow',
  'tablet',
  'mobile-2',
  'movie',
  'calendar-2',
  'baseball',
  'basketball',
  'art-gallery',
  'industrial-building',
  'campsite',
  'cinema',
  'london-underground',
  'lodging',
  'toilet',
  'town-hall',
  'theatre',
  'tennis',
  'swimming',
  'soccer',
  'school',
  'restaurant',
  'police',
  'giraffe',
  'football',
  'fire-station',
  'ferry',
  'fast-food',
  'blind',
  'guidedog',
  'glasses',
  'chart',
  'address-book',
  'key-1',
] as const;

export type FontelloName = typeof fontelloName[number];

interface FaIconDef {
  name: string;
  key: IconName;
  library: 'fa' | 'far';
}

interface FontelloDef {
  name: string;
  key: FontelloName;
  library: 'icon';
}

export type IconDef = FaIconDef | FontelloDef;

export const icons: IconDef[] = [
  { name: 'Game', key: 'gamepad', library: 'fa' },
  { name: 'Automobile', key: 'car', library: 'fa' },
  { name: 'Beer', key: 'beer', library: 'fa' },
  { name: 'University', key: 'university', library: 'fa' },
  { name: 'Bell', key: 'bell', library: 'fa' },
  { name: 'Chart', key: 'chart-bar', library: 'fa' },
  { name: 'Bed', key: 'bed', library: 'fa' },
  { name: 'Bicycle', key: 'bicycle', library: 'fa' },
  { name: 'Binoculars', key: 'binoculars', library: 'fa' },
  { name: 'Birthday', key: 'birthday-cake', library: 'fa' },
  { name: 'Bold', key: 'bolt', library: 'fa' },
  { name: 'Bomb', key: 'bomb', library: 'fa' },
  { name: 'Book', key: 'book', library: 'fa' },
  { name: 'Briefcase', key: 'briefcase', library: 'fa' },
  { name: 'Bug', key: 'bug', library: 'fa' },
  { name: 'Building', key: 'building', library: 'fa' },
  { name: 'Bullhorn', key: 'bullhorn', library: 'fa' },
  { name: 'Bus', key: 'bus', library: 'fa' },
  { name: 'Taxi', key: 'taxi', library: 'fa' },
  { name: 'Calculator', key: 'calculator', library: 'fa' },
  { name: 'Calendar', key: 'calendar', library: 'fa' },
  { name: 'Camera', key: 'camera', library: 'fa' },
  { name: 'Person', key: 'child', library: 'fa' },
  { name: 'Cloud', key: 'cloud', library: 'fa' },
  { name: 'Clock', key: 'clock', library: 'far' },
  { name: 'Code', key: 'code', library: 'fa' },
  { name: 'Code fork', key: 'code-branch', library: 'fa' },
  { name: 'Coffee', key: 'coffee', library: 'fa' },
  { name: 'Cogs', key: 'cogs', library: 'fa' },
  { name: 'Comment', key: 'comment', library: 'fa' },
  { name: 'Discussion', key: 'comments', library: 'fa' },
  { name: 'Compass', key: 'compass', library: 'fa' },
  { name: 'Credit card', key: 'credit-card', library: 'fa' },
  { name: 'Crop', key: 'crop', library: 'fa' },
  { name: 'Database', key: 'database', library: 'fa' },
  { name: 'Desktop', key: 'desktop', library: 'fa' },
  { name: 'Letter', key: 'envelope', library: 'fa' },
  { name: 'Exclamation', key: 'exclamation', library: 'fa' },
  { name: 'Exchange', key: 'exchange-alt', library: 'fa' },
  { name: 'Eye', key: 'eye', library: 'fa' },
  { name: 'Eyedropper', key: 'eye-dropper', library: 'fa' },
  { name: 'Fax', key: 'fax', library: 'fa' },
  { name: 'Woman', key: 'female', library: 'fa' },
  { name: 'Fighter jet', key: 'fighter-jet', library: 'fa' },
  { name: 'Fire', key: 'fire', library: 'fa' },
  { name: 'Fire extinguisher', key: 'fire-extinguisher', library: 'fa' },
  { name: 'Flag', key: 'flag', library: 'fa' },
  { name: 'Flask', key: 'flask', library: 'fa' },
  { name: 'Football', key: 'futbol', library: 'fa' },
  { name: 'Gavel', key: 'gavel', library: 'fa' },
  { name: 'Gift', key: 'gift', library: 'fa' },
  { name: 'Glass', key: 'glass-martini-alt', library: 'fa' },
  { name: 'World', key: 'globe', library: 'fa' },
  { name: 'Graduation', key: 'graduation-cap', library: 'fa' },
  { name: 'Hard disk', key: 'hdd', library: 'far' },
  { name: 'Headphones', key: 'headphones', library: 'fa' },
  { name: 'Heart', key: 'heart', library: 'fa' },
  { name: 'Heartbeat', key: 'heartbeat', library: 'fa' },
  { name: 'Home', key: 'home', library: 'fa' },
  { name: 'Inbox', key: 'inbox', library: 'fa' },
  { name: 'Info', key: 'info', library: 'fa' },
  { name: 'Key', key: 'key', library: 'fa' },
  { name: 'Keyboard', key: 'keyboard', library: 'far' },
  { name: 'Life ring', key: 'life-ring', library: 'fa' },
  { name: 'Laptop', key: 'laptop', library: 'fa' },
  { name: 'Lightbulb', key: 'lightbulb', library: 'far' },
  { name: 'Leaf', key: 'leaf', library: 'fa' },
  { name: 'Chart', key: 'chart-line', library: 'fa' },
  { name: 'Location arrow', key: 'location-arrow', library: 'fa' },
  { name: 'Lock', key: 'lock', library: 'fa' },
  { name: 'Magic', key: 'magic', library: 'fa' },
  { name: 'Magnet', key: 'magnet', library: 'fa' },
  { name: 'Men', key: 'male', library: 'fa' },
  { name: 'Map marker', key: 'map-marker', library: 'fa' },
  { name: 'Microphone', key: 'microphone', library: 'fa' },
  { name: 'Mobile', key: 'mobile', library: 'fa' },
  { name: 'Money', key: 'money-bill', library: 'fa' },
  { name: 'Motorcycle', key: 'motorcycle', library: 'fa' },
  { name: 'Music', key: 'music', library: 'fa' },
  { name: 'Newspaper', key: 'newspaper', library: 'far' },
  { name: 'Paint brush', key: 'paint-brush', library: 'fa' },
  { name: 'Paper plane', key: 'paper-plane', library: 'fa' },
  { name: 'Animal paw', key: 'paw', library: 'fa' },
  { name: 'Phone', key: 'phone', library: 'fa' },
  { name: 'Pie chart', key: 'chart-pie', library: 'fa' },
  { name: 'Plane', key: 'plane', library: 'fa' },
  { name: 'Plug', key: 'plug', library: 'fa' },
  { name: 'Power off', key: 'power-off', library: 'fa' },
  { name: 'Print', key: 'print', library: 'fa' },
  { name: 'Puzzle', key: 'puzzle-piece', library: 'fa' },
  { name: 'Quote left', key: 'quote-left', library: 'fa' },
  { name: 'Quote right', key: 'quote-right', library: 'fa' },
  { name: 'Random', key: 'random', library: 'fa' },
  { name: 'Recycle', key: 'recycle', library: 'fa' },
  { name: 'Road', key: 'road', library: 'fa' },
  { name: 'Rocket', key: 'rocket', library: 'fa' },
  { name: 'Search', key: 'search', library: 'fa' },
  { name: 'RSS', key: 'rss', library: 'fa' },
  { name: 'Server', key: 'server', library: 'fa' },
  { name: 'Shopping cart', key: 'shopping-cart', library: 'fa' },
  { name: 'Signal', key: 'signal', library: 'fa' },
  { name: 'Star', key: 'star', library: 'fa' },
  { name: 'Spoon', key: 'utensil-spoon', library: 'fa' },
  { name: 'Suitcase', key: 'suitcase', library: 'fa' },
  { name: 'Tablet', key: 'tablet', library: 'fa' },
  { name: 'Street view', key: 'street-view', library: 'fa' },
  { name: 'Tag', key: 'tag', library: 'fa' },
  { name: 'Tags', key: 'tags', library: 'fa' },
  { name: 'Tasks', key: 'tasks', library: 'fa' },
  { name: 'Terminal', key: 'terminal', library: 'fa' },
  { name: 'Thumbs down', key: 'thumbs-down', library: 'fa' },
  { name: 'Thumbs up', key: 'thumbs-up', library: 'fa' },
  { name: 'Ticket', key: 'ticket-alt', library: 'fa' },
  { name: 'Tint', key: 'tint', library: 'fa' },
  { name: 'Tree', key: 'tree', library: 'fa' },
  { name: 'Trophy', key: 'trophy', library: 'fa' },
  { name: 'Truck', key: 'truck', library: 'fa' },
  { name: 'Umbrella', key: 'umbrella', library: 'fa' },
  { name: 'Unlock', key: 'unlock-alt', library: 'fa' },
  { name: 'Wheelchair', key: 'wheelchair', library: 'fa' },
  { name: 'Wrench', key: 'wrench', library: 'fa' },
  { name: 'Ambulance', key: 'ambulance', library: 'fa' },
  { name: 'Syringe', key: 'syringe', library: 'fa' },
  { name: 'Brain', key: 'brain', library: 'fa' },
  { name: 'Vial', key: 'vial', library: 'fa' },
  { name: 'Vials', key: 'vials', library: 'fa' },
  { name: 'Virus', key: 'virus', library: 'fa' },
  { name: 'Bacteria', key: 'bacteria', library: 'fa' },
  { name: 'Subway', key: 'subway', library: 'fa' },
  { name: 'Train', key: 'train', library: 'fa' },
  { name: 'Space shuttle', key: 'space-shuttle', library: 'fa' },
  { name: 'Chain', key: 'link', library: 'fa' },
  { name: 'Chain broken', key: 'unlink', library: 'fa' },
  { name: 'Scissors', key: 'cut', library: 'fa' },
  { name: 'Paperclip', key: 'paperclip', library: 'fa' },
  { name: 'Stethoscope', key: 'stethoscope', library: 'fa' },
  { name: 'Doctor', key: 'user-md', library: 'fa' },
  { name: 'Medical kit', key: 'medkit', library: 'fa' },
  { name: 'ID card', key: 'id-card', library: 'far' },
  { name: 'Invoice', key: 'file-invoice', library: 'fa' },
  { name: 'Receipt', key: 'receipt', library: 'fa' },
  { name: 'User', key: 'user', library: 'fa' },
  { name: 'Users', key: 'users', library: 'fa' },
  { name: 'Emo ungry', key: 'emo-angry', library: 'icon' },
  { name: 'Emo beer', key: 'emo-beer', library: 'icon' },
  { name: 'Emo saint', key: 'emo-saint', library: 'icon' },
  { name: 'Emo cry', key: 'emo-cry', library: 'icon' },
  { name: 'Emo shoot', key: 'emo-shoot', library: 'icon' },
  { name: 'Emo squint', key: 'emo-squint', library: 'icon' },
  { name: 'Emo laugh', key: 'emo-laugh', library: 'icon' },
  { name: 'Emo displeased', key: 'emo-displeased', library: 'icon' },
  { name: 'Emo sunglasses', key: 'emo-sunglasses', library: 'icon' },
  { name: 'Emo coffee', key: 'emo-coffee', library: 'icon' },
  { name: 'Emo tongue', key: 'emo-tongue', library: 'icon' },
  { name: 'Emo surprised', key: 'emo-surprised', library: 'icon' },
  { name: 'Emo devil', key: 'emo-devil', library: 'icon' },
  { name: 'emo-thumbsup', key: 'emo-thumbsup', library: 'icon' },
  { name: 'emo-sleep', key: 'emo-sleep', library: 'icon' },
  { name: 'emo-unhappy', key: 'emo-unhappy', library: 'icon' },
  { name: 'emo-wink2', key: 'emo-wink2', library: 'icon' },
  { name: 'emo-wink', key: 'emo-wink', library: 'icon' },
  { name: 'emo-happy', key: 'emo-happy', library: 'icon' },
  { name: 'note', key: 'note', library: 'icon' },
  { name: 'note-beamed', key: 'note-beamed', library: 'icon' },
  { name: 'flashlight', key: 'flashlight', library: 'icon' },
  { name: 'heart', key: 'heart', library: 'icon' },
  { name: 'user', key: 'user', library: 'icon' },
  { name: 'video', key: 'video', library: 'icon' },
  { name: 'picture', key: 'picture', library: 'icon' },
  { name: 'camera', key: 'camera', library: 'icon' },
  { name: 'tag', key: 'tag', library: 'icon' },
  { name: 'comment', key: 'comment', library: 'icon' },
  { name: 'book', key: 'book', library: 'icon' },
  { name: 'hourglass', key: 'hourglass', library: 'icon' },
  { name: 'sound', key: 'sound', library: 'icon' },
  { name: 'lock', key: 'lock', library: 'icon' },
  { name: 'lock-open', key: 'lock-open', library: 'icon' },
  { name: 'pencil', key: 'pencil', library: 'icon' },
  { name: 'feather', key: 'feather', library: 'icon' },
  { name: 'print', key: 'print', library: 'icon' },
  { name: 'info', key: 'info', library: 'icon' },
  { name: 'share', key: 'share', library: 'icon' },
  { name: 'tools', key: 'tools', library: 'icon' },
  { name: 'bell', key: 'bell', library: 'icon' },
  { name: 'alert', key: 'alert', library: 'icon' },
  { name: 'chat', key: 'chat', library: 'icon' },
  { name: 'folder', key: 'folder', library: 'icon' },
  { name: 'archive', key: 'archive', library: 'icon' },
  { name: 'box', key: 'box', library: 'icon' },
  { name: 'bookmark', key: 'bookmark', library: 'icon' },
  { name: 'bookmarks', key: 'bookmarks', library: 'icon' },
  { name: 'compass', key: 'compass', library: 'icon' },
  { name: 'basket', key: 'basket', library: 'icon' },
  { name: 'lamp', key: 'lamp', library: 'icon' },
  { name: 'light-up', key: 'light-up', library: 'icon' },
  { name: 'trophy', key: 'trophy', library: 'icon' },
  { name: 'battery', key: 'battery', library: 'icon' },
  { name: 'back-in-time', key: 'back-in-time', library: 'icon' },
  { name: 'monitor', key: 'monitor', library: 'icon' },
  { name: 'mobile', key: 'mobile', library: 'icon' },
  { name: 'palette', key: 'palette', library: 'icon' },
  { name: 'signal', key: 'signal', library: 'icon' },
  { name: 'progress-3', key: 'progress-3', library: 'icon' },
  { name: 'progress-2', key: 'progress-2', library: 'icon' },
  { name: 'progress-1', key: 'progress-1', library: 'icon' },
  { name: 'book-open', key: 'book-open', library: 'icon' },
  { name: 'newspaper', key: 'newspaper', library: 'icon' },
  { name: 'doc-text-inv', key: 'doc-text-inv', library: 'icon' },
  { name: 'doc-text', key: 'doc-text', library: 'icon' },
  { name: 'mic', key: 'mic', library: 'icon' },
  { name: 'chart-pie', key: 'chart-pie', library: 'icon' },
  { name: 'chart-line', key: 'chart-line', library: 'icon' },
  { name: 'chart-bar', key: 'chart-bar', library: 'icon' },
  { name: 'chart-area', key: 'chart-area', library: 'icon' },
  { name: 'cloud-thunder', key: 'cloud-thunder', library: 'icon' },
  { name: 'globe', key: 'globe', library: 'icon' },
  { name: 'network', key: 'network', library: 'icon' },
  { name: 'cd', key: 'cd', library: 'icon' },
  { name: 'magnet', key: 'magnet', library: 'icon' },
  { name: 'brush', key: 'brush', library: 'icon' },
  { name: 'infinity', key: 'infinity', library: 'icon' },
  { name: 'key', key: 'key', library: 'icon' },
  { name: 'bucket', key: 'bucket', library: 'icon' },
  { name: 'database', key: 'database', library: 'icon' },
  { name: 'megaphone', key: 'megaphone', library: 'icon' },
  { name: 'clipboard', key: 'clipboard', library: 'icon' },
  { name: 'floppy', key: 'floppy', library: 'icon' },
  { name: 'credit-card', key: 'credit-card', library: 'icon' },
  { name: 'droplet', key: 'droplet', library: 'icon' },
  { name: 'water', key: 'water', library: 'icon' },
  { name: 'air', key: 'air', library: 'icon' },
  { name: 'ticket', key: 'ticket', library: 'icon' },
  { name: 'graduation-cap', key: 'graduation-cap', library: 'icon' },
  { name: 'tape', key: 'tape', library: 'icon' },
  { name: 'flash', key: 'flash', library: 'icon' },
  { name: 'moon', key: 'moon', library: 'icon' },
  { name: 'flight', key: 'flight', library: 'icon' },
  { name: 'lifebuoy', key: 'lifebuoy', library: 'icon' },
  { name: 'mouse', key: 'mouse', library: 'icon' },
  { name: 'briefcase', key: 'briefcase', library: 'icon' },
  { name: 'suitcase', key: 'suitcase', library: 'icon' },
  { name: 'dot', key: 'dot', library: 'icon' },
  { name: 'dot-2', key: 'dot-2', library: 'icon' },
  { name: 'dot-3', key: 'dot-3', library: 'icon' },
  { name: 'flow-tree', key: 'flow-tree', library: 'icon' },
  { name: 'flow-branch', key: 'flow-branch', library: 'icon' },
  { name: 'flow-cascade', key: 'flow-cascade', library: 'icon' },
  { name: 'flow-line', key: 'flow-line', library: 'icon' },
  { name: 'gauge', key: 'gauge', library: 'icon' },
  { name: 'flow-parallel', key: 'flow-parallel', library: 'icon' },
  { name: 'thermometer', key: 'thermometer', library: 'icon' },
  { name: 'list-add', key: 'list-add', library: 'icon' },
  { name: 'list', key: 'list', library: 'icon' },
  { name: 'target', key: 'target', library: 'icon' },
  { name: 'play', key: 'play', library: 'icon' },
  { name: 'stop', key: 'stop', library: 'icon' },
  { name: 'pause', key: 'pause', library: 'icon' },
  { name: 'record', key: 'record', library: 'icon' },
  { name: 'to-end', key: 'to-end', library: 'icon' },
  { name: 'to-start', key: 'to-start', library: 'icon' },
  { name: 'fast-forward', key: 'fast-forward', library: 'icon' },
  { name: 'fast-backward', key: 'fast-backward', library: 'icon' },
  { name: 'bag', key: 'bag', library: 'icon' },
  { name: 'calendar', key: 'calendar', library: 'icon' },
  { name: 'docs', key: 'docs', library: 'icon' },
  { name: 'doc', key: 'doc', library: 'icon' },
  { name: 'doc-landscape', key: 'doc-landscape', library: 'icon' },
  { name: 'code', key: 'code', library: 'icon' },
  { name: 'user-outline', key: 'user-outline', library: 'icon' },
  { name: 'user-1', key: 'user-1', library: 'icon' },
  { name: 'users-outline', key: 'users-outline', library: 'icon' },
  { name: 'users', key: 'users', library: 'icon' },
  { name: 'user-add-outline', key: 'user-add-outline', library: 'icon' },
  { name: 'user-add', key: 'user-add', library: 'icon' },
  { name: 'user-delete-outline', key: 'user-delete-outline', library: 'icon' },
  { name: 'user-delete', key: 'user-delete', library: 'icon' },
  { name: 'video-1', key: 'video-1', library: 'icon' },
  { name: 'videocam-outline', key: 'videocam-outline', library: 'icon' },
  { name: 'videocam', key: 'videocam', library: 'icon' },
  { name: 'picture-outline', key: 'picture-outline', library: 'icon' },
  { name: 'picture-1', key: 'picture-1', library: 'icon' },
  { name: 'camera-outline', key: 'camera-outline', library: 'icon' },
  { name: 'camera-1', key: 'camera-1', library: 'icon' },
  { name: 'th-outline', key: 'th-outline', library: 'icon' },
  { name: 'th', key: 'th', library: 'icon' },
  { name: 'th-large-outline', key: 'th-large-outline', library: 'icon' },
  { name: 'th-large', key: 'th-large', library: 'icon' },
  { name: 'th-list-outline', key: 'th-list-outline', library: 'icon' },
  { name: 'th-list', key: 'th-list', library: 'icon' },
  { name: 'anchor', key: 'anchor', library: 'icon' },
  { name: 'pi', key: 'pi', library: 'icon' },
  { name: 'chart-pie-alt', key: 'chart-pie-alt', library: 'icon' },
  { name: 'chart-pie-1', key: 'chart-pie-1', library: 'icon' },
  { name: 'aperture', key: 'aperture', library: 'icon' },
  { name: 'aperture-alt', key: 'aperture-alt', library: 'icon' },
  { name: 'steering-wheel', key: 'steering-wheel', library: 'icon' },
  { name: 'book-1', key: 'book-1', library: 'icon' },
  { name: 'brush-1', key: 'brush-1', library: 'icon' },
  { name: 'brush-alt', key: 'brush-alt', library: 'icon' },
  { name: 'equalizer', key: 'equalizer', library: 'icon' },
  { name: 'chart-bar-1', key: 'chart-bar-1', library: 'icon' },
  { name: 'umbrella', key: 'umbrella', library: 'icon' },
  { name: 'moon-inv', key: 'moon-inv', library: 'icon' },
  { name: 'mobile-1', key: 'mobile-1', library: 'icon' },
  { name: 'split', key: 'split', library: 'icon' },
  { name: 'target-1', key: 'target-1', library: 'icon' },
  { name: 'calendar-1', key: 'calendar-1', library: 'icon' },
  { name: 'wrench', key: 'wrench', library: 'icon' },
  { name: 'bullhorn', key: 'bullhorn', library: 'icon' },
  { name: 'award', key: 'award', library: 'icon' },
  { name: 'signal-1', key: 'signal-1', library: 'icon' },
  { name: 'money', key: 'money', library: 'icon' },
  { name: 'dollar', key: 'dollar', library: 'icon' },
  { name: 'lock-1', key: 'lock-1', library: 'icon' },
  { name: 'lock-open-1', key: 'lock-open-1', library: 'icon' },
  { name: 'home', key: 'home', library: 'icon' },
  { name: 'trash', key: 'trash', library: 'icon' },
  { name: 'videocam-alt', key: 'videocam-alt', library: 'icon' },
  { name: 'camera-2', key: 'camera-2', library: 'icon' },
  { name: 'videocam-1', key: 'videocam-1', library: 'icon' },
  { name: 'windy-rain-inv', key: 'windy-rain-inv', library: 'icon' },
  { name: 'snow-inv', key: 'snow-inv', library: 'icon' },
  { name: 'snow-heavy-inv', key: 'snow-heavy-inv', library: 'icon' },
  { name: 'hail-inv', key: 'hail-inv', library: 'icon' },
  { name: 'clouds-inv', key: 'clouds-inv', library: 'icon' },
  { name: 'clouds-flash-inv', key: 'clouds-flash-inv', library: 'icon' },
  { name: 'temperature', key: 'temperature', library: 'icon' },
  { name: 'compass-1', key: 'compass-1', library: 'icon' },
  { name: 'cloud-sun-inv', key: 'cloud-sun-inv', library: 'icon' },
  { name: 'cloud-moon-inv', key: 'cloud-moon-inv', library: 'icon' },
  { name: 'cloud-flash-inv', key: 'cloud-flash-inv', library: 'icon' },
  { name: 'cloud-inv', key: 'cloud-inv', library: 'icon' },
  { name: 'drizzle-inv', key: 'drizzle-inv', library: 'icon' },
  { name: 'rain-inv', key: 'rain-inv', library: 'icon' },
  { name: 'windy-inv', key: 'windy-inv', library: 'icon' },
  { name: 'sun-inv', key: 'sun-inv', library: 'icon' },
  { name: 'moon-inv-1', key: 'moon-inv-1', library: 'icon' },
  { name: 'ruler', key: 'ruler', library: 'icon' },
  { name: 'fire', key: 'fire', library: 'icon' },
  { name: 'trophy-1', key: 'trophy-1', library: 'icon' },
  { name: 'female', key: 'female', library: 'icon' },
  { name: 'male', key: 'male', library: 'icon' },
  { name: 'spread', key: 'spread', library: 'icon' },
  { name: 'king', key: 'king', library: 'icon' },
  { name: 'monitor-1', key: 'monitor-1', library: 'icon' },
  { name: 'coverflow', key: 'coverflow', library: 'icon' },
  { name: 'tablet', key: 'tablet', library: 'icon' },
  { name: 'mobile-2', key: 'mobile-2', library: 'icon' },
  { name: 'movie', key: 'movie', library: 'icon' },
  { name: 'calendar-2', key: 'calendar-2', library: 'icon' },
  { name: 'baseball', key: 'baseball', library: 'icon' },
  { name: 'basketball', key: 'basketball', library: 'icon' },
  { name: 'art-gallery', key: 'art-gallery', library: 'icon' },
  { name: 'industrial-building', key: 'industrial-building', library: 'icon' },
  { name: 'campsite', key: 'campsite', library: 'icon' },
  { name: 'cinema', key: 'cinema', library: 'icon' },
  { name: 'london-underground', key: 'london-underground', library: 'icon' },
  { name: 'lodging', key: 'lodging', library: 'icon' },
  { name: 'toilet', key: 'toilet', library: 'icon' },
  { name: 'town-hall', key: 'town-hall', library: 'icon' },
  { name: 'theatre', key: 'theatre', library: 'icon' },
  { name: 'tennis', key: 'tennis', library: 'icon' },
  { name: 'swimming', key: 'swimming', library: 'icon' },
  { name: 'soccer', key: 'soccer', library: 'icon' },
  { name: 'school', key: 'school', library: 'icon' },
  { name: 'restaurant', key: 'restaurant', library: 'icon' },
  { name: 'police', key: 'police', library: 'icon' },
  { name: 'giraffe', key: 'giraffe', library: 'icon' },
  { name: 'cat', key: 'cat', library: 'fa' },
  { name: 'paw', key: 'paw', library: 'fa' },
  { name: 'football', key: 'football', library: 'icon' },
  { name: 'fire-station', key: 'fire-station', library: 'icon' },
  { name: 'ferry', key: 'ferry', library: 'icon' },
  { name: 'fast-food', key: 'fast-food', library: 'icon' },
  { name: 'blind', key: 'blind', library: 'icon' },
  { name: 'guidedog', key: 'guidedog', library: 'icon' },
  { name: 'glasses', key: 'glasses', library: 'icon' },
  { name: 'chart', key: 'chart', library: 'icon' },
  { name: 'address-book', key: 'address-book', library: 'icon' },
  { name: 'key-1', key: 'key-1', library: 'icon' },
];

export function getIconDef(library: string, key: string): IconDef | undefined {
  return icons.find(icon => icon.key === key && icon.library === library);
}
