angular.module('wegas.service.customize', [])
.factory('Customize', function(Flash) {
	var colors = [
		'orange', 'blue', 'red', 'yellow', 
		'purple','pink', 'green', 'grey'
		],
		icons = [
			{name: "Game", key: "gamepad"},
			{name: "Automobile", key:"car"},
			{name: "Beer", key:"beer"},
			{name: "University", key:"university"},
			{name: "Bell", key:"bell"},
			{name: "Chart", key:"bar-chart"},
			{name: "Bed", key:"bed"},
			{name: "Bicycle", key:"bicycle"},
			{name: "Binoculars", key:"binoculars"},
			{name: "Birthday", key:"birthday-cake"},
			{name: "Bold", key:"bolt"},
			{name: "Bomb", key:"bomb"},
			{name: "Book", key:"book"},
			{name: "Briefcase", key:"briefcase"},
			{name: "Bug", key:"bug"},
			{name: "Building", key:"building"},
			{name: "Bullhorn", key:"bullhorn"},
			{name: "Bus", key:"bus"},
			{name: "Taxi", key:"taxi"},
			{name: "Calculator", key:"calculator"},
			{name: "Calendar", key:"calendar"},
			{name: "Camera", key:"camera"},
			{name: "Person", key:"child"},
			{name: "Cloud", key:"cloud"},
			{name: "Clock", key:"clock-o"},
			{name: "Code", key:"code"},
			{name: "Code fork", key:"code-fork"},
			{name: "Coffee", key:"coffee"},
			{name: "Cogs", key:"cogs"},
			{name: "Comment", key:"comment"},
			{name: "Discussion", key:"comments"},
			{name: "Compass", key:"compass"},
			{name: "Credit card", key:"credit-card"},
			{name: "Crop", key:"crop"},
			{name: "Database", key:"database"},
			{name: "Desktop", key:"desktop"},
			{name: "Letter", key:"envelope"},
			{name: "Exclamation", key:"exclamation"},
			{name: "Exchange", key:"exchange"},
			{name: "Eye", key:"eye"},
			{name: "Eyedropper", key:"eyedropper"},
			{name: "Fax", key:"fax"},
			{name: "Woman", key:"female"},
			{name: "Fighter jet", key:"fighter-jet"},
			{name: "Fire", key:"fire"},
			{name: "Fire extinguisher", key:"fire-extinguisher"},
			{name: "Flag", key:"flag"},
			{name: "Flask", key:"flask"},
			{name: "Football", key:"futbol-o"},
			{name: "Gavel", key:"gavel"},
			{name: "Gift", key:"gift"},
			{name: "Glass", key:"glass"},
			{name: "World", key:"globe"},
			{name: "Graduation", key:"graduation-cap"},
			{name: "Hard disk", key:"hdd-o"},
			{name: "Headphones", key:"headphones"},
			{name: "Heart", key:"heart"},
			{name: "Heartbeat", key:"heartbeat"},
			{name: "Home", key:"home"},
			{name: "Inbox", key:"inbox"},
			{name: "Info", key:"info"},
			{name: "Key", key:"key"},
			{name: "Keyboard", key:"keyboard-o"},
			{name: "Life ring", key:"life-ring"},
			{name: "Laptop", key:"laptop"},
			{name: "Lightbulb", key:"lightbulb-o"},
			{name: "Leaf", key:"leaf"},
			{name: "Chart", key:"line-chart"},
			{name: "Location arrow", key:"location-arrow"},
			{name: "Lock", key:"lock"},
			{name: "Magic", key:"magic"},
			{name: "Magnet", key:"magnet"},
			{name: "Men", key:"male"},
			{name: "Map marker", key:"map-marker"},
			{name: "Microphone", key:"microphone"},
			{name: "Mobile", key:"mobile"},
			{name: "Money", key:"money"},
			{name: "Motorcycle", key:"motorcycle"},
			{name: "Music", key:"music"},
			{name: "Newspaper", key:"newspaper-o"},
			{name: "Paint brush", key:"paint-brush"},
			{name: "Paper plane", key:"paper-plane"},
			{name: "Animal paw", key:"paw"},
			{name: "Phone", key:"phone"},
			{name: "Pie chart", key:"pie-chart"},
			{name: "Plane", key:"plane"},
			{name: "Plug", key:"plug"},
			{name: "Power off", key:"power-off"},
			{name: "Print", key:"print"},
			{name: "Puzzle", key:"puzzle-piece"},
			{name: "Quote left", key:"quote-left"},
			{name: "Quote right", key:"quote-right"},
			{name: "Random", key:"random"},
			{name: "Recycle", key:"recycle"},
			{name: "Road", key:"road"},
			{name: "Rocket", key:"rocket"},
			{name: "Search", key:"search"},
			{name: "RSS", key:"rss"},
			{name: "Server", key:"server"},
			{name: "Shopping cart", key:"shopping-cart"},
			{name: "Signal", key:"signal"},
			{name: "Star", key:"star"},
			{name: "Spoon", key:"spoon"},
			{name: "Suitcase", key:"suitcase"},
			{name: "Tablet", key:"tablet"},
			{name: "Street view", key:"street-view"},
			{name: "Tag", key:"tag"},
			{name: "Tags", key:"tags"},
			{name: "Tasks", key:"tasks"},
			{name: "Terminal", key:"terminal"},
			{name: "Thumbs down", key:"thumbs-down"},
			{name: "Thumbs up", key:"thumbs-up"},
			{name: "Ticket", key:"ticket"},
			{name: "Tint", key:"tint"},
			{name: "Tree", key:"tree"},
			{name: "Trophy", key:"trophy"},
			{name: "Truck", key:"truck"},
			{name: "Umbrella", key:"umbrella"},
			{name: "Unlock", key:"unlock-alt"},
			{name: "Wheelchair", key:"wheelchair"},
			{name: "Wrench", key:"wrench"},
			{name: "Ambulance", key:"ambulance"},
			{name: "Subway", key:"subway"},
			{name: "Train", key:"train"},
			{name: "Space shuttle", key:"space-shuttle"},
			{name: "Chain", key:"link"},
			{name: "Chain broken", key:"chain-broken"},
			{name: "Scissors", key:"scissors"},
			{name: "Paperclip", key:"paperclip"},
			{name: "Stethoscope", key:"stethoscope"},
			{name: "Doctor", key:"user-md"},
			{name: "Medical kit", key:"medkit"}
		];
	return {
		colorsPalette: function(){
			return colors;
		},
		iconsPalette: function(){
			return icons;
		}
	};
});