// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9505baf036887c87e752cbc7b1e137f8b2f023e4/react-color/lib/components/material/Material.d.ts
declare module 'react-color/lib/components/material/material' {
import { Component } from 'react';
import { ColorPickerProps } from 'react-color';

export type MaterialPickerProps = ColorPickerProps<MaterialPicker>;

export default class MaterialPicker extends Component<MaterialPickerProps, any> {}
}
