// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9505baf036887c87e752cbc7b1e137f8b2f023e4/react-color/lib/components/sketch/Sketch.d.ts
declare module 'react-color/lib/components/sketch/sketch' {
import { Component } from 'react';
import { ColorPickerProps } from 'react-color';

export interface SketchPickerProps extends ColorPickerProps<SketchPicker> {
    disableAlpha?: boolean;
    presetColors?: string[];
    width?: string;
}

export default class SketchPicker extends Component<SketchPickerProps, any> {}
}
