// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9505baf036887c87e752cbc7b1e137f8b2f023e4/react-color/lib/components/compact/Compact.d.ts
declare module 'react-color/lib/components/compact/compact' {
import { Component } from 'react';
import { ColorPickerProps } from 'react-color';

export interface CompactPickerProps extends ColorPickerProps<CompactPicker> {
    colors?: string[];
}

export default class CompactPicker extends Component<CompactPickerProps, any> {}
}
